baseURL = 'https://blog.cxx.pub/'
defaultContentLanguage = 'zh-cn'
locale = 'zh-CN'
title = 'IMXBlog'

[params]
  description = '真相一旦入眼，你无法视而不见！'
  subtitle = '真相一旦入眼，你无法视而不见。'
  author = 'IMX'
  avatar = '/images/imx/imx.jpg'
  mainSections = ['posts']
  keywords = ['技术博客', 'JavaScript', 'Python', 'Go', 'Java', 'C++', '编程']

  [params.social]
    github = 'https://github.com/c-x-x'
    email = 'cxxpub@proton.me'

  [params.giscus]
    enabled = true
    repo = "c-x-x/blog-comments"
    repoId = "R_kgDOS5n9Lw"
    category = "Announcements"
    categoryId = "DIC_kwDOS5n9L84C_FGp"
    mapping = "pathname"
    lang = "zh-CN"
    lightTheme = "light"
    darkTheme = "dark"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'dracula'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"

  [markup.goldmark.parser.attribute]
    block = true
    title = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[outputFormats.JSON]
  mediaType = 'application/json'
  baseName = 'index'
  isPlainText = true

[module]
  [[module.imports]]
    path = 'github.com/c-x-x/hugo-theme-imx'
